[package]
name = "unic-ucd-utils"
version = "0.4.0"
authors = ["The UNIC Project Developers"]
homepage = "https://github.com/behnam/rust-unic/"
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
keywords = ["text", "unicode"]
description = "UNIC - Utilities for working with Unicode Code Points"

exclude = [ "tests/*conformance*.rs" ]

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
