[package]
name = "unic-gen"
version = "0.0.1"
authors = ["The UNIC Project Developers"]
homepage = "https://github.com/behnam/rust-unic/"
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
keywords = ["text", "unicode"]
description = "UNIC - Unicode Character Database - Table Generation"
readme = "README.md"

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
