[package]
name = "unic-char-range"
version = "0.5.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
keywords = ["text", "unicode", "iteration"]
description = "UNIC - CharRange"
categories = ["text-processing", "iteration"]
readme = "README.md"

# No tests/benches that depends on /data/
exclude = []

[features]
default = []

# Unstable features
unstable = [ "associated-consts", "fused", "trusted-len" ]
associated-consts = []
fused = []
trusted-len = []

[dependencies]

[badges]
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
